language: elixir
elixir:
  - 1.4.0
otp_release:
  - 19.1
sudo: false
env:
  - MIX_ENV=test
before_install:
  - nvm install 6.9.4 && nvm use 6.9.4
before_script:
  - phantomjs --wd >/dev/null 2>&1 &
  - sleep 1
  - npm install
  - npm run deploy
  - npm run elm-make
script:
  - "mix do local.hex --force, deps.get, test"
cache:
  directories:
    - node_modules
    - deps
    - _build
    - elm-stuff
    - web/static/elm/tests/elm-stuff
deploy:
  provider: heroku
  api-key: e3216652-61f5-4d94-9b30-c6008279c68a